CREATE DATABASE SENAI_HROADS_TARDE

CREATE TABLE PERSONAGEM(
	idPersonagem SMALLINT PRIMARY KEY IDENTITY,
	nome VARCHAR(20),
	capmaxVida TINYINT NOT NULL,
	capmaxMana TINYINT NOT NULL,
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	dataCriacao DATE NOT NULL,
	dataAtualizacao DATE
);

CREATE TABLE CLASSE(
	idClasse TINYINT PRIMARY KEY IDENTITY,
	nome VARCHAR(20) NOT NULL,
);

CREATE TABLE TIPOHABILIDADE(
	idtipoHabilidade TINYINT PRIMARY KEY IDENTITY,
	nome VARCHAR(20) NOT NULL,
);

CREATE TABLE HABILIDADE(
	idHabilidade INT PRIMARY KEY IDENTITY,
	nome VARCHAR(25),
	idtipoHabilidade TINYINT FOREIGN KEY REFERENCES TIPOHABILIDADE(idtipoHabilidade),
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse),
);

