CREATE DATABASE T_InLock_Games_Jhon;
GO

USE T_InLock_Games_Jhon;
GO

CREATE TABLE ESTUDIO(
 idEstudio SMALLINT PRIMARY KEY IDENTITY,
 nomeEstudio VARCHAR(150) NOT NULL UNIQUE
);
GO
CREATE TABLE JOGO(
 idJogo INT PRIMARY KEY IDENTITY,
 idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio),
 nomeJogo VARCHAR(180) NOT NULL,
 descricao TEXT NOT NULL,
 dataLancamento DATE NOT NULL,
 valor SMALLMONEY NOT NULL
);
GO
CREATE TABLE TIPOUSUARIO(
 idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
 titulo VARCHAR(100) NOT NULL UNIQUE
);
GO
CREATE TABLE USUARIO(
 idUsuario INT PRIMARY KEY IDENTITY,
 idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
 email VARCHAR(150) NOT NULL UNIQUE,
 senha VARCHAR(25) NOT NULL
);
GO

